### ISSUE TITLE
add support for higher version of .NET core

### ISSUE THREAD

**Issue by Xephobia** [nonunknown/crowbarx#1]
It erros about not finding a framework, the current version of .NET core is 5

**Comment by nonunknown** [comment]
plz make a more detailed bug information, with error message, screenshots if applicable! 

also .net core is cross platform, others arent and .net core is the latest version: https://dotnet.microsoft.com/download/dotnet/3.1

![image](https://user-images.githubusercontent.com/58845030/128070389-d1254213-a151-4c7f-9be5-69dc7a040fe1.png)

**Comment by Xephobia** [comment]
```
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.8 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=manjaro-x64
```
I use manjaro and installed net core with pacman with `pacman -S dotnet-sdk dotnet-runtime`
`dotnet --version` gives 5.0.205

**Comment by Xephobia** [comment]
so i seems the version required is the LTS, but i have the most recent version

**Comment by nonunknown** [comment]
if yout version were higher then it should  work ok! I'm on manjaro too!

`dotnet --version`
3.1.411
